# Denne fil er allerede hånteret af AKS.
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginxapp1-ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx  # i aks er der også en anden controller man anvender.
spec:  
  rules:
  - http:
      paths:
      - path: /
        pathType: prefix
        backend:
          #serviceName: app1-nginx-clusterip-service
          service:
            name: app1-nginx-clusterip-service
          #servicePort: 80
            port: 
              number: 80

  
